# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'TheMovieBox' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
    pod 'Alamofire'
    pod 'Default'
    pod 'Kingfisher', '~> 7.0'

  # Pods for TheMovieBox

  target 'TheMovieBoxTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'TheMovieBoxUITests' do
    # Pods for testing
  end

end
